name: Feature Request
description: Suggest a new feature or enhancement for Full Self Coding
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem or use case this feature would address...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions or features you've considered...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component of FSC would this feature affect?
      options:
        - Analyzer
        - TaskSolver
        - DockerInstance
        - ConfigReader
        - CodeCommitter
        - Agent Integration (Claude/Gemini/Codex)
        - CLI/Configuration
        - Documentation
        - Other
    validations:
      required: false

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      description: What would this feature impact?
      options:
        - label: Breaking change (requires migration)
        - label: Performance improvement
        - label: Developer experience
        - label: User experience
        - label: Security enhancement
        - label: Documentation update needed

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, examples, or information about the feature request
      placeholder: Add any other context, screenshots, or examples here...

